name 'install_mongodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_mongodb'
long_description 'Installs/Configures install_mongodb'
version '0.1.0'
